# Generated by Django 6.1.1 on 2026-09-14 10:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(help_text='Ex: Accès Wi-Fi 5G, Support 24/7, Débit 10 Mbps', max_length=255, unique=True, verbose_name='Libellé du contenu')),
            ],
            options={
                'verbose_name': 'Contenu disponible',
                'verbose_name_plural': 'Contenus disponibles',
                'db_table': 'contenu',
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, verbose_name="Nom de l'entreprise")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='enterprises/logos/', verbose_name="Logo de l'entreprise")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'db_table': 'enterprise',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name="Nom de l'opérateur")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='operators/logos/', verbose_name="Logo de l'opérateur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Opérateur',
                'verbose_name_plural': 'Opérateurs',
                'db_table': 'operator',
            },
        ),
        migrations.CreateModel(
            name='Prise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prise', models.CharField(max_length=100, verbose_name='Prise / Port réseau')),
            ],
            options={
                'verbose_name': 'Prise',
                'verbose_name_plural': 'Prises',
                'db_table': 'prise',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=100, verbose_name='Nom')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Forfait',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=150, verbose_name='Titre du forfait')),
                ('prix', models.IntegerField(default=0, verbose_name='Prix (FCFA)')),
                ('duree_minutes', models.IntegerField(default=60, verbose_name='Durée de validité (en minutes)')),
                ('contenus', models.ManyToManyField(blank=True, related_name='forfaits', to='captive_portal.contenu', verbose_name='Contenus inclus')),
            ],
            options={
                'verbose_name': 'Forfait',
                'verbose_name_plural': 'Forfaits',
                'db_table': 'forfait',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('numero', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('mac_adresse', models.CharField(blank=True, max_length=17, null=True, verbose_name='Adresse MAC')),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dernière IP connue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_users', to='captive_portal.enterprise', verbose_name='Entreprise')),
                ('pole_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pole_de_service_users', to='captive_portal.service', verbose_name='Pôle de service')),
            ],
            options={
                'verbose_name': 'Utilisateur Réseau',
                'verbose_name_plural': 'Utilisateurs Réseau',
                'db_table': 'network_users',
            },
        ),
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_paiement', models.CharField(help_text='Numéro utilisé pour le paiement (ex: Orange Money, MTN MoMo, Wave)', max_length=20, verbose_name='Numéro de téléphone / Paiement')),
                ('montant_paye', models.IntegerField(default=0, verbose_name='Montant payé (FCFA)')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('ECHEC', 'Échec / Annulé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut de la souscription')),
                ('date_heure_souscription', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de souscription')),
                ('date_expiration', models.DateTimeField(blank=True, null=True, verbose_name="Date et heure d'expiration")),
                ('forfait', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='souscriptions', to='captive_portal.forfait', verbose_name='Forfait souscrit')),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='souscriptions', to='captive_portal.operator', verbose_name='Opérateur de paiement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions', to='captive_portal.user', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Souscription',
                'verbose_name_plural': 'Souscriptions',
                'db_table': 'souscription',
                'ordering': ['-date_heure_souscription'],
            },
        ),
        migrations.CreateModel(
            name='Connexion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_connexion', models.CharField(choices=[('ACTIF', 'En cours'), ('TERMINE', 'Terminée'), ('COUPE', 'Coupée / Expirée'), ('ECHEC', 'Échec de connexion')], default='ACTIF', max_length=20, verbose_name='Statut de la connexion')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('adresse_mac', models.CharField(blank=True, max_length=17, null=True, verbose_name='Adresse MAC')),
                ('debut_connexion', models.DateTimeField(auto_now_add=True, verbose_name='Début de connexion')),
                ('fin_connexion', models.DateTimeField(blank=True, null=True, verbose_name='Fin de connexion')),
                ('souscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connexions', to='captive_portal.souscription', verbose_name='Souscription utilisée')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connexions', to='captive_portal.user', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Connexion Réseau',
                'verbose_name_plural': 'Connexions Réseau',
                'db_table': 'connexion',
                'ordering': ['-debut_connexion'],
            },
        ),
    ]
