# Generated by Django 6.1.1 on 2026-09-16 18:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captive_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiusAcctLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acct_session_id', models.CharField(db_index=True, max_length=64, verbose_name='Session ID RADIUS')),
                ('username', models.CharField(max_length=64, verbose_name='MAC / Username')),
                ('input_octets', models.BigIntegerField(default=0, verbose_name='Download (AcctInputOctets)')),
                ('output_octets', models.BigIntegerField(default=0, verbose_name='Upload (AcctOutputOctets)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
            ],
            options={
                'verbose_name': 'Journal Accounting RADIUS',
                'verbose_name_plural': 'Journaux Accounting RADIUS',
                'db_table': 'radius_acct_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='connexion',
            name='acct_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Session ID RADIUS (Acct-Session-Id)'),
        ),
        migrations.AddField(
            model_name='connexion',
            name='derniere_mise_a_jour',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernier paquet Accounting'),
        ),
        migrations.AddField(
            model_name='connexion',
            name='nas_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP du NAS / pfSense'),
        ),
        migrations.AddField(
            model_name='connexion',
            name='octets_entrants',
            field=models.BigIntegerField(default=0, verbose_name='Download (Octets)'),
        ),
        migrations.AddField(
            model_name='connexion',
            name='octets_sortants',
            field=models.BigIntegerField(default=0, verbose_name='Upload (Octets)'),
        ),
        migrations.AddField(
            model_name='connexion',
            name='prise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connexions', to='captive_portal.prise', verbose_name='Prise utilisée'),
        ),
        migrations.AddField(
            model_name='forfait',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Forfait actif'),
        ),
        migrations.AddField(
            model_name='forfait',
            name='bandwidth_max_down',
            field=models.IntegerField(default=10485760, help_text='WISPr-Bandwidth-Max-Down. Exemple: 10 Mbps = 10485760', verbose_name='Débit Max Descendant (bps)'),
        ),
        migrations.AddField(
            model_name='forfait',
            name='bandwidth_max_up',
            field=models.IntegerField(default=5242880, help_text='WISPr-Bandwidth-Max-Up. Exemple: 5 Mbps = 5242880', verbose_name='Débit Max Montant (bps)'),
        ),
        migrations.AddField(
            model_name='forfait',
            name='prises',
            field=models.ManyToManyField(blank=True, help_text='Prises/ports réseau sur lesquels ce forfait est utilisable', related_name='forfaits', to='captive_portal.prise', verbose_name='Prises associées / autorisées'),
        ),
        migrations.AddField(
            model_name='forfait',
            name='quota_octets',
            field=models.BigIntegerField(default=0, help_text='0 pour Illimité. Exemple: 1 Go = 1073741824 octets', verbose_name='Quota Data (en Octets)'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='pfsense_guest', max_length=128, verbose_name='Password RADIUS'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Format standardisé (ex: AA:BB:CC:DD:EE:FF)', max_length=64, null=True, unique=True, verbose_name='Username RADIUS / MAC Cleaned'),
        ),
        migrations.AlterField(
            model_name='connexion',
            name='adresse_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP client'),
        ),
        migrations.AlterField(
            model_name='connexion',
            name='adresse_mac',
            field=models.CharField(blank=True, db_index=True, max_length=17, null=True, verbose_name='Adresse MAC'),
        ),
        migrations.AlterField(
            model_name='connexion',
            name='status_connexion',
            field=models.CharField(choices=[('ACTIF', 'En cours'), ('TERMINE', 'Terminée'), ('COUPE', 'Coupée par CoA (Quota/Admin)'), ('EXPIRE', 'Expirée (Temps dépassé)'), ('ECHEC', 'Échec de connexion')], db_index=True, default='ACTIF', max_length=20, verbose_name='Statut de la connexion'),
        ),
        migrations.AlterField(
            model_name='prise',
            name='prise',
            field=models.CharField(help_text='Ex: Prise RJ45-A101', max_length=100, unique=True, verbose_name='Prise / Port réseau'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mac_adresse',
            field=models.CharField(blank=True, db_index=True, max_length=17, null=True, verbose_name='Adresse MAC'),
        ),
    ]
