# Generated by Django 6.1.1 on 2026-09-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captive_portal', '0002_radiusacctlog_connexion_acct_session_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nasname', models.TextField()),
                ('shortname', models.TextField()),
                ('type', models.TextField(default='other')),
                ('ports', models.IntegerField(blank=True, null=True)),
                ('secret', models.TextField()),
                ('server', models.TextField(blank=True, null=True)),
                ('community', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadAcct',
            fields=[
                ('radacctid', models.BigAutoField(db_column='RadAcctId', primary_key=True, serialize=False)),
                ('acctsessionid', models.TextField(db_column='AcctSessionId')),
                ('acctuniqueid', models.TextField(db_column='AcctUniqueId', unique=True)),
                ('username', models.TextField(blank=True, db_column='UserName', null=True)),
                ('realm', models.TextField(blank=True, db_column='Realm', null=True)),
                ('nasipaddress', models.GenericIPAddressField(db_column='NASIPAddress')),
                ('nasportid', models.TextField(blank=True, db_column='NASPortId', null=True)),
                ('nasporttype', models.TextField(blank=True, db_column='NASPortType', null=True)),
                ('acctstarttime', models.DateTimeField(blank=True, db_column='AcctStartTime', null=True)),
                ('acctupdatetime', models.DateTimeField(blank=True, db_column='AcctUpdateTime', null=True)),
                ('acctstoptime', models.DateTimeField(blank=True, db_column='AcctStopTime', null=True)),
                ('acctinterval', models.BigIntegerField(blank=True, db_column='AcctInterval', null=True)),
                ('acctsessiontime', models.BigIntegerField(blank=True, db_column='AcctSessionTime', null=True)),
                ('acctauthentic', models.TextField(blank=True, db_column='AcctAuthentic', null=True)),
                ('connectinfo_start', models.TextField(blank=True, db_column='ConnectInfo_start', null=True)),
                ('connectinfo_stop', models.TextField(blank=True, db_column='ConnectInfo_stop', null=True)),
                ('acctinputoctets', models.BigIntegerField(blank=True, db_column='AcctInputOctets', null=True)),
                ('acctoutputoctets', models.BigIntegerField(blank=True, db_column='AcctOutputOctets', null=True)),
                ('calledstationid', models.TextField(blank=True, db_column='CalledStationId', null=True)),
                ('callingstationid', models.TextField(blank=True, db_column='CallingStationId', null=True)),
                ('acctterminatecause', models.TextField(blank=True, db_column='AcctTerminateCause', null=True)),
                ('servicetype', models.TextField(blank=True, db_column='ServiceType', null=True)),
                ('framedprotocol', models.TextField(blank=True, db_column='FramedProtocol', null=True)),
                ('framedipaddress', models.GenericIPAddressField(blank=True, db_column='FramedIPAddress', null=True)),
                ('framedipv6address', models.GenericIPAddressField(blank=True, db_column='FramedIPv6Address', null=True, protocol='IPv6')),
                ('framedipv6prefix', models.GenericIPAddressField(blank=True, db_column='FramedIPv6Prefix', null=True, protocol='IPv6')),
                ('framedinterfaceid', models.TextField(blank=True, db_column='FramedInterfaceId', null=True)),
                ('delegatedipv6prefix', models.GenericIPAddressField(blank=True, db_column='DelegatedIPv6Prefix', null=True, protocol='IPv6')),
                ('raw_class', models.TextField(blank=True, db_column='Class', null=True)),
            ],
            options={
                'db_table': 'radacct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadCheck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(db_column='UserName', default='')),
                ('attribute', models.TextField(db_column='Attribute', default='')),
                ('op', models.CharField(default='==', max_length=2)),
                ('value', models.TextField(db_column='Value', default='')),
            ],
            options={
                'db_table': 'radcheck',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(db_column='UserName', default='')),
                ('attribute', models.TextField(db_column='Attribute', default='')),
                ('op', models.CharField(default='=', max_length=2)),
                ('value', models.TextField(db_column='Value', default='')),
            ],
            options={
                'db_table': 'radreply',
                'managed': False,
            },
        ),
    ]
