# Generated by Django 6.1.1 on 2026-09-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captive_portal', '0003_nas_radacct_radcheck_radreply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nas',
            options={'managed': False, 'verbose_name': 'NAS / Pare-feu (pfSense)', 'verbose_name_plural': 'NAS / Pare-feux (pfSense)'},
        ),
        migrations.AlterModelOptions(
            name='radacct',
            options={'managed': False, 'verbose_name': 'FreeRADIUS - Session Accounting', 'verbose_name_plural': 'FreeRADIUS - Sessions Accounting'},
        ),
        migrations.AlterModelOptions(
            name='radcheck',
            options={'managed': False, 'verbose_name': 'FreeRADIUS - Check', 'verbose_name_plural': 'FreeRADIUS - Checks'},
        ),
        migrations.AlterModelOptions(
            name='radreply',
            options={'managed': False, 'verbose_name': 'FreeRADIUS - Reply', 'verbose_name_plural': 'FreeRADIUS - Replies'},
        ),
    ]
