# Generated by Django 6.1.1 on 2026-09-24 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captive_portal', '0004_alter_nas_options_alter_radacct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='souscription',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='Identifiant unique fourni par la passerelle de paiement (ex: CinetPay)', max_length=100, null=True, unique=True, verbose_name='ID Transaction Paiement'),
        ),
        migrations.AlterField(
            model_name='souscription',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('ECHEC', 'Échec / Annulé')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='Statut de la souscription'),
        ),
        migrations.AlterField(
            model_name='user',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_users', to='captive_portal.enterprise', verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pole_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pole_de_service_users', to='captive_portal.service', verbose_name='Pôle de service'),
        ),
    ]
