# Generated by Django 6.1.1 on 2026-09-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captive_portal', '0005_souscription_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service / Pôle', 'verbose_name_plural': 'Services / Pôles'},
        ),
        migrations.AddField(
            model_name='operator',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code API Opérateur (ex: OM, WAVE)'),
        ),
        migrations.AddField(
            model_name='souscription',
            name='payment_token',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Jeton de paiement API'),
        ),
        migrations.AlterField(
            model_name='radiusacctlog',
            name='username',
            field=models.CharField(db_index=True, max_length=64, verbose_name='MAC / Username'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(max_length=100, verbose_name='Nom du service'),
        ),
        migrations.AlterField(
            model_name='souscription',
            name='numero_paiement',
            field=models.CharField(max_length=20, verbose_name='Numéro de téléphone / Paiement'),
        ),
        migrations.AlterField(
            model_name='user',
            name='numero',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, help_text='Format standardisé (ex: AA:BB:CC:DD:EE:FF)', max_length=64, null=True, unique=True, verbose_name='Username RADIUS / MAC Cleaned'),
        ),
    ]
