# Generated by Django 6.1.1 on 2026-09-29 09:15

import captive_portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captive_portal', '0006_alter_service_options_operator_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forfait',
            name='simultaneous_use',
            field=models.IntegerField(default=1, verbose_name='Sessions simultanées max'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=captive_portal.models.generate_secure_password, max_length=128, verbose_name='Password RADIUS'),
        ),
    ]
